spring:
  application:
    name: cloud-config-server
  cloud:
      config:
        server:
          git:
            uri: git@github.com:yangweixin/config-repo.git
  #          searchPaths: spring_cloud_in_action/config-repo
            username: young
            password: 123456
server:
  port: 7400
